config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :tickets
  resources :users

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/campu.rb
class Campu < ActiveRecord::Base
end

app/models/priority.rb
class Priority < ActiveRecord::Base
end

app/models/request_type.rb
class RequestType < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :ticket
end

app/models/you_are.rb
class YouAre < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:first_namme, :last_name, :job_title, :phone_number, :department, :needed_by, :email_id, :priority, :are_you, :type_of_request, :purpose_of_request, :description_of_request, :time_period, :student_type, :campus, :irb, :grant_pi, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_namme, :last_name, :phone_number, :email_id, :unit, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OiaTicketing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
  Logged in as <strong><%= current_admin.email %></strong>.
  <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
<% end %></p>
<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_namme %><br>
    <%= f.text_field :first_namme %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :job_title %><br>
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :needed_by %><br>
    <%= f.date_select :needed_by %>
  </div>
  <div class="field">
    <%= f.label :email_id %><br>
    <%= f.text_field :email_id %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :are_you %><br>
    <%= f.text_field :are_you %>
  </div>
  <div class="field">
    <%= f.label :type_of_request %><br>
    <%= f.text_field :type_of_request %>
  </div>
  <div class="field">
    <%= f.label :purpose_of_request %><br>
    <%= f.text_area :purpose_of_request %>
  </div>
  <div class="field">
    <%= f.label :description_of_request %><br>
    <%= f.text_area :description_of_request %>
  </div>
  <div class="field">
    <%= f.label :time_period %><br>
    <%= f.number_field :time_period %>
  </div>
  <div class="field">
    <%= f.label :student_type %><br>
    <%= f.text_field :student_type %>
  </div>
  <div class="field">
    <%= f.label :campus %><br>
    <%= f.collection_select :campus, Campu.all, :id, :name %>    
  </div>
  <div class="field">
    <%= f.label :irb %><br>
    <%= f.number_field :irb %>
  </div>
  <div class="field">
    <%= f.label :grant_pi %><br>
    <%= f.text_field :grant_pi %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
    <tr>
      <th>First namme</th>
      <th>Last name</th>
      <th>Job title</th>
      <th>Phone number</th>
      <th>Department</th>
      <th>Needed by</th>
      <th>Email</th>
      <th>Priority</th>
      <th>Are you</th>
      <th>Type of request</th>
      <th>Purpose of request</th>
      <th>Description of request</th>
      <th>Time period</th>
      <th>Student type</th>
      <th>Campus</th>
      <th>Irb</th>
      <th>Grant pi</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.first_namme %></td>
        <td><%= ticket.last_name %></td>
        <td><%= ticket.job_title %></td>
        <td><%= ticket.phone_number %></td>
        <td><%= ticket.department %></td>
        <td><%= ticket.needed_by %></td>
        <td><%= ticket.email_id %></td>
        <td><%= ticket.priority %></td>
        <td><%= ticket.are_you %></td>
        <td><%= ticket.type_of_request %></td>
        <td><%= ticket.purpose_of_request %></td>
        <td><%= ticket.description_of_request %></td>
        <td><%= ticket.time_period %></td>
        <td><%= ticket.student_type %></td>
        <td><%= ticket.campus %></td>
        <td><%= ticket.irb %></td>
        <td><%= ticket.grant_pi %></td>
        <td><%= ticket.user %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First namme:</strong>
  <%= @ticket.first_namme %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @ticket.last_name %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @ticket.job_title %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @ticket.phone_number %>
</p>

<p>
  <strong>Department:</strong>
  <%= @ticket.department %>
</p>

<p>
  <strong>Needed by:</strong>
  <%= @ticket.needed_by %>
</p>

<p>
  <strong>Email:</strong>
  <%= @ticket.email_id %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @ticket.priority %>
</p>

<p>
  <strong>Are you:</strong>
  <%= @ticket.are_you %>
</p>

<p>
  <strong>Type of request:</strong>
  <%= @ticket.type_of_request %>
</p>

<p>
  <strong>Purpose of request:</strong>
  <%= @ticket.purpose_of_request %>
</p>

<p>
  <strong>Description of request:</strong>
  <%= @ticket.description_of_request %>
</p>

<p>
  <strong>Time period:</strong>
  <%= @ticket.time_period %>
</p>

<p>
  <strong>Student type:</strong>
  <%= @ticket.student_type %>
</p>

<p>
  <strong>Campus:</strong>
  <%= @ticket.campus %>
</p>

<p>
  <strong>Irb:</strong>
  <%= @ticket.irb %>
</p>

<p>
  <strong>Grant pi:</strong>
  <%= @ticket.grant_pi %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket.user %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_namme %><br>
    <%= f.text_field :first_namme %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email_id %><br>
    <%= f.text_field :email_id %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First namme</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Unit</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_namme %></td>
        <td><%= user.last_name %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.email_id %></td>
        <td><%= user.unit %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First namme:</strong>
  <%= @user.first_namme %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email_id %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @user.unit %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>